# seed for Comments
Comment.delete_all
["Love this!",
"Thanks for passing this on.",
"I can't believe I missed that!",
"Don't forget to look out for #1",
"Check yourself before you wreck yourself",
"We should remember this when brainstorming for phase 2.",
"Yes, please.",
"WWJPD?",
"Whomp, whomp.",
"That's what she said!",
"That's what your mom said!",
"That's what Anthony Weiner said!",
"Happy birthday!",
"What's up with that? Chuck sucks.",
"Me too.",
"FIRST!",
"Agreed!",
"Yo, where you at?",
"Nailed it!",
"Booooring.",
"$10 isn't cool. You know what's cool? $100!",
"HTTP 503 Service Unavailable.  Please try e-Breaux again later.",
"I'm drinking that Kool-Aid!",
"Is it just me, or does this make you hungry for some dog fooding?",
"This reminds me, I found a 9th for our Groundr team! Ready to play ball?",
"C'mon man, approve my vacation request. I worked day and night—DAY AND NIGHT—to get the app ready for the product demos. I just need a few days off.",
"You remind me of [insert same music/movie reference here]",
"What do you say that we go do [insert activity gerund] and unprotected sex?",
"Not enough characters allowed in a comment for me to agree with this as much as I do",
"What!? That's my favorite comic /sci-fi /or video game too!",
"What a handsome idea!",
"Just like an artificially flavored cloud intelligence would -( best if from Catherine)",
"Totally! DRM has given this media such a short shelf life",
"When will everyone else recognize that responsive design enables technically superior websites and physically superior designers",
"More misunderstood than Peter Parker, more smart than Richards, more dapper than Tony Stark",
"Few posts have such well crafted words and or more notable thoughts",
"Who's been cast as Joseph Price for the movie?",
"Every now and then I have to remind myself how amazing you are",
"Wasn't it the Post that called you the most prophetic facebook poster of our generation?",
"There are not enough words to describe this post",
"Truer words were never spoken.",
"Seriously?!?",
"Wah-wah.",
"Joe, who does your hair?",
"Congrats! It's about time!",
"I've heard about this before. Not a shock.",
"Get her done!",
"Really dude, you totally earned it.",
"Hey, that's my mom your talking about. Just kidding, breaux!  Well done!",
"Here we go again!",
"I'm so happy for you! Yay!",
"Now i'm jealous.",
"That's why they pay you the big bucks.",
"Aww, man!  That sucks, pal.",
"You and me both!",
"We should all be so lucky.",
"NOT!",
"We should go out and get drunks together."].each do |m|
  Comment.find_or_create_by_message(m)
end