require 'rack/oauth2'

class FacebooksController < ApplicationController
  before_filter :require_authentication, :only => :destroy

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    begin
      auth = Facebook.auth.from_cookie(cookies)
      fb = Facebook.identify(auth.user)

      # verify fb account and set session id
      authenticate fb

      # valid facebook account found, pull details
      profile = FbGraph::User.me(fb.access_token).fetch
      fb.first_name = profile.first_name
      fb.last_name = profile.last_name
      fb.save

      # redirect_to dashboard_url
      redirect_to :controller => :dashboard, :action => :index

    rescue Exception => e
      logger.error "Error: " + e.message
      # logger.error e.backtrace.inspect
      flash[:notice] = "An error has occurred while communicating with Facebook"
      redirect_to root_url
    end
  end


  def impersonate
    session[:current_user] = params[:id]
    redirect_to root_url
  end
  # 
  # # handle Normal OAuth flow: start
  # def new
  #   redirect_to client.authorization_uri(
  #     :scope => Facebook.config[:perms]
  #   )
  # end
  # 
  # # handle Normal OAuth flow: callback
  # def create
  #   # save code and access_token
  #   client.authorization_code = params[:code]
  #   access_token = client.access_token!
  #   
  #   # fetch user details (identifier)
  #   user = FbGraph::User.me(access_token).fetch
  # 
  #   # create facebook record if needed; save session/cookie data
  #   Facebook.identify(user)
  #   
  #   # redirect to confirmation_url
  #   redirect_to :action => :confirm
  # end
  # 
  # def confirm
  #   
  # end

  private

  def client
    unless @client
      @client = Facebook.auth.client
      @client.redirect_uri = callback_facebook_url
    end
    @client
  end

end
