require 'rack/oauth2'

class FacebooksController < ApplicationController
  before_filter :require_authentication, :only => :destroy

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    begin
      auth = Facebook.auth.from_cookie(cookies)
      fb = Facebook.identify(auth.user)

      # verify fb account and set session id
      authenticate fb

      # valid facebook account found, pull details
      profile = FbGraph::User.me(fb.access_token).fetch
      fb.first_name = profile.first_name
      fb.last_name = profile.last_name
      fb.save

      # redirect_to dashboard_url
      redirect_to :controller => :dashboard, :action => :index

    rescue Exception => e
      logger.error "Error: " + e.message
      # logger.error e.backtrace.inspect
      flash[:notice] = "An error has occurred while communicating with Facebook"
      redirect_to root_url
    end
  end


  private

  def client
    unless @client
      @client = Facebook.auth.client
      @client.redirect_uri = callback_facebook_url
    end
    @client
  end

end
